name: EC2 Controller CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required for OIDC
      contents: read    # For actions/checkout
      
    steps:
      - name:
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install boto3

      - name: Package Lambda code
        run: zip -r lambda-package.zip lambda_function.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::703671897239:role/OIDC-GitHub
          role-session-name: OIDC-GitHub
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          # Check if Lambda exists
          if aws lambda get-function --function-name EC2-Controller --region ${{ secrets.AWS_REGION }} 2>/dev/null; then
            aws lambda update-function-code \
              --function-name EC2-Controller \
              --zip-file fileb://lambda-package.zip \
              --region ${{ secrets.AWS_REGION }}
          else
            aws lambda create-function \
              --function-name EC2-Controller \
              --runtime python3.9 \
              --role arn:aws:iam::703671897239:role/OIDC-GitHub \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://lambda-package.zip \
              --environment "Variables={INSTANCE_IDS=${{ secrets.INSTANCE_IDS }}}" \
              --region ${{ secrets.AWS_REGION }}
          fi