name: EC2 Controller CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required for OIDC
      contents: read    # For actions/checkout
      
    steps:
      - name:
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::703671897239:role/OIDC-GitHub
          role-session-name: OIDC-GitHub
          aws-region: ${{ env.AWS_REGION }}
