name: Deploy S3 Bucket and Upload File with Terraform
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615299761831:role/github-action.oidc
          aws-region: us-east-1

      - name: Debug AWS credentials
        run: aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Create test file
        run: echo "This is a test file uploaded via Terraform!!!!!!" > test-file.txt

      - name: Move test file to terraform directory
        run: mv test-file.txt terraform/

      - name: Debug directory contents
        run: ls -la terraform/
        working-directory: .

      - name: Terraform Init
        run: terraform init -no-color
        working-directory: terraform
        env:
          TF_LOG: DEBUG

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        working-directory: terraform

      - name: Terraform Output
        run: terraform output bucket_name
        working-directory: terraform