name: Create S3 Bucket and Upload File

on:
  push:
    branches:
      - '**'
    

permissions:
  id-token: write
  contents: read

jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::615299761831:role/github.oidc
          aws-region: us-east-1

      - name: Create a test file
        run: |
          echo "This is a tests file uploaded by GitHub Actions." > test-file.txt

      - name: Create S3 Bucket
        run: |
          BUCKET_NAME=github-actions-test-$(date +%s)
          echo "Bucket name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1

      - name: Upload file to S3
        run: |
          aws s3 cp test-file.txt s3://$BUCKET_NAME/

            - name: Print GitHub OIDC Token (for debug only)
        id: debug-token

      - name: testing OIDC  
        run: |
          echo "Requesting OIDC Token..."
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
          echo "OIDC Token:"
          echo $TOKEN | jq .    